baseURL = "https://docs.mendix.com/"
title = "Mendix Documentation"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]
themesDir = "node_modules"

# NK - Changes default ERROR message when unable to resolve ref/relref links to WARNING
# Are we going to use this?
refLinksErrorLevel = "WARNING"

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true
languageCode = "en-us"

disableKinds = ["taxonomy", "term"]

# Image processing configuration. (Do we use this - probably not?)
[imaging]
    resampleFilter = "CatmullRom"
    quality = 75
    anchor = "smart"

[services]
    [services.googleAnalytics]
        # Marketing Google Tag ID
        id = 'UA-163813-1'

# Language configuration

[languages]
    [languages.en]
        languageName ="English"
        # Weight used for sorting.
        weight = 1

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
        # See config options at https://gohugo.io/getting-started/configuration-markup/#highlight
        style = "pygments" # DB - Changed default style for accessibility (see https://www.ctmartin.me/blog/2019/11/print-accessible-code/)
        lineNos = false # DB - Turned off line numbers as the default. Can turn them on individually, if required, but this causes the copy button to disappear.
        guessSyntax = true # DB - Maintain styling when no language is specified
    # NK - set up table of contents to support correct depth for our document structure
    [markup.tableOfContents]
        endLevel = 6
        ordered = false
        startLevel = 2

[module]
replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
    section = ["HTML", "print"]
    # MvM - add line below to print every page
    page = ["HTML", "print"]

# MvM - add line below to activate production of RSS pages
[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "rss"

# MvM - Set default priority for sitemap = 0.5
# Can override in front matter for each section using
# cascade:
#     - sitemap:
#         priority = 0.0
# 
[sitemap]
    priority = 0.5

# Everything below this are Site Params
# ======================================
# These are mainly (all?) Docsy settings

[params]
    copyright = "Â© Mendix Technology BV 2021. All rights reserved."
    privacy_policy = "http://www.mendix.com/privacy-policy/"

    # Menu title if your navbar has a versions selector to access old versions of your site.
    # This menu appears only if you have at least one [params.versions] set.
    version_menu = "Releases"

    # Flag used in the "version-banner" partial to decide whether to display a 
    # banner on every page indicating that this is an archived version of the docs.
    # Set this flag to "true" if you want to display the banner.
    archived_version = false

    # The version number for the version of the docs represented in this doc set.
    # Used in the "version-banner" partial to display a version number for the 
    # current doc set.
    version = "0.0"

    # A link to latest version of the docs. Used in the "version-banner" partial to
    # point people to the main doc site.
    url_latest_version = "https://docs.mendix.com/"

    # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
    # ==========================================================================================
    github_repo = "https://github.com/mendix/docs"
    # Specify development branch for GitHub links (e.g. to edit)
    github_branch= "development"

    # An optional link to a related project repo. For example, the sibling repository where your product code lives.
    # github_project_repo = "https://github.com/google/docsy"
    # Specify a value here if your content directory is not in your repo's root directory
    # github_subdir = ""

    # Google Custom Search Engine ID. Remove or comment out to disable search.
    #gcs_engine_id = "d72aa9b2712488cc3"

    # Algolia DocSearch
    search.algolia = false

    # Lunr.js offline search
    offlineSearch = false

    # First one is picked as the Twitter card image if not set on page.
    # images = ["images/project-illustration.png"]

    # NK - taxonomy section adds the tag cloud to the ToC section - need to comment out "disableKinds"
    # NK - values can be empty to not have tags, instead of commented out
    [params.taxonomy]
        taxonomyCloud = [] #["tags"] # set taxonomyCloud = [] to hide taxonomy clouds
        taxonomyCloudTitle = [] # if used, must have same lang as taxonomyCloud
        taxonomyPageHeader = [] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

    # User interface configuration
    [params.ui]
        # Enable to show the side bar menu in its compact state.
        sidebar_menu_compact = true
        #  Set to true to disable breadcrumb navigation.
        breadcrumb_disable = false
        #  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
        sidebar_search_disable = true
        #  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
        navbar_logo = false
        # Set to true to disable the About link in the site footer
        footer_about_disable = true
        # NK - set sidebar to be foldable
        sidebar_menu_foldable = true

    # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
    # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
    # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
    # add "hide_feedback: true" to the page's front matter.
    [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Glad to hear it! Thank you for your response.'
        no = 'Sorry to hear that. Please <a href="https://github.com/mendix/docs/issues/new">tell us how we can improve</a>.'
    # Adds a reading time to the top of each doc.
    # If you want this feature, but occasionally need to remove the Reading time from a single page, 
    # add "hide_readingtime: true" to the page's front matter
    [params.ui.readingtime]
        enable = false

    [params.links]
        # End user relevant links. These will show up on left side of footer and in the community page if you have one.
        [[params.links.user]]
        	name = "User mailing list"
        	url = "https://example.org/mail"
        	icon = "fa fa-envelope"
            desc = "Discussion and help from your fellow users"
        [[params.links.user]]
        	name ="Twitter"
        	url = "https://example.org/twitter"
        	icon = "fab fa-twitter"
            desc = "Follow us on Twitter to get the latest news!"
        [[params.links.user]]
        	name = "Stack Overflow"
        	url = "https://example.org/stack"
        	icon = "fab fa-stack-overflow"
            desc = "Practical questions and curated answers"
        # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
        [[params.links.developer]]
        	name = "GitHub"
        	url = "https://github.com/google/docsy"
        	icon = "fab fa-github"
            desc = "Development takes place here!"
        [[params.links.developer]]
        	name = "Developer mailing list"
        	url = "https://example.org/mail"
        	icon = "fa fa-envelope"
            desc = "Discuss development issues around the project"
