# Site settings
name: Mendix
description: ""
url: "https://docs.mendix.com"
baseurl: ""
encoding: utf-8

# Base variables
latest_major_version: "6"
github_repo: "https://github.com/mendix/docs"
github_branch: "development"
title: "Mendix Documentation"

timezone: Netherlands/Amsterdam
permalink: ordinal

####################################
######        ALGOLIA        #######
####################################

algolia:
  application_id:    'OHBX5T982M'
  index_name:        'documentation'
  read_only_api_key: 'd23e5ac47b71a0f51afa5fedc695b718'
  excluded_files:
    - index.html
    - howto6/index.html
    - howto50/index.html
    - refguide6/index.html
    - refguide5/index.html
    - search/index.html
  settings:
    attributesForFaceting:
      - 'tags'
      - 'type'
      - 'title'
      - 'space'

####################################
######        SPACES         #######
####################################
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: mxdefault

  # VERSION SPECIFIC CONTENT
  # Mendix 6
  - scope:
      path: 'howto6'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'refguide6'
      type: pages
    values:
      menus:
        - "refguide6"
        - "community"
  # Mendix 5
  - scope:
      path: 'howto50'
      type: pages
    values:
      menus:
        - "howto50"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
      #banner: 'exportfromconfluence5'
  - scope:
      path: 'refguide5'
      type: pages
    values:
      menus:
        - "refguide5"
        - "community"
      #banner: 'exportfromconfluence5'

  # VERSION INDEPENDENT
  - scope:
      path: 'community'
      type: pages
    values:
      space: "Community"
      menus:
        - "refguide6"
        - "community"
  - scope:
      path: 'apidocs'
      type: pages
    values:
      menus:
        - "apidocs"
  - scope:
      path: 'ATS'
      type: pages
    values:
      menus:
        - "ATS"
  - scope:
      path: 'APM'
      type: pages
    values:
      menus:
        - "APM"
  - scope:
      path: 'MXSDK'
      type: pages
    values:
      menus:
        - "MXSDK"
  - scope:
      path: 'mxsupport'
      type: pages
    values:
      menus:
        - "mxsupport"
  - scope:
      path: 'tips'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'bestpractices'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'appstore'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"
  - scope:
      path: 'mendixcloud'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "appstore"
        - "mendixcloud"

####################################

exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.lock.osx
  - Gemfile.lock.win
  - README.md
  - Rakefile
  - node_modules
  - vendor
  - package.json
  - test.txt
  - run.bat
  - manifest.yml
  - community/The+How+to+Template.md
  - community/The+Reference+Guide+Page+Template.md
  - CONTRIBUTING.md

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - algoliasearch-jekyll
