# Site settings
name: "Mendix Documentation"
description: "Mendix documentation"
url: "https://docs.mendix.com"
baseurl: ""
encoding: utf-8
locale: "en_US"

# Base variables
latest_major_version: "7"
github_repo: "https://github.com/mendix/docs"
github_branch: "development"
title: "Mendix Documentation"

timezone: Netherlands/Amsterdam
permalink: ordinal

####################################
######        ALGOLIA        #######
####################################

algolia:
  application_id:    'OHBX5T982M'
  index_name:        'docs'
  read_only_api_key: 'd23e5ac47b71a0f51afa5fedc695b718'


####################################
######        SPACES         #######
####################################
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: mxdefault

  # VERSION SPECIFIC CONTENT
  # Mendix 7
  - scope:
      path: 'howto7'
      type: pages
    values:
      menus:
        - "howto7"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
  - scope:
      path: 'refguide7'
      type: pages
    values:
      menus:
        - "refguide7"
  # Mendix 6
  - scope:
      path: 'howto6'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
  - scope:
      path: 'refguide6'
      type: pages
    values:
      menus:
        - "refguide6"
  # Mendix 5
  - scope:
      path: 'howto50'
      type: pages
    values:
      menus:
        - "howto50"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
  - scope:
      path: 'refguide5'
      type: pages
    values:
      menus:
        - "refguide5"
  # Mendix 4
  - scope:
      path: 'howto40'
      type: pages
    values:
      menus:
        - "howto40"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
      banner: "mendix4howto"
  - scope:
      path: 'refguide4'
      type: pages
    values:
      menus:
        - "refguide4"
      banner: "mendix4refguide"

  # VERSION INDEPENDENT
  - scope:
      path: 'community'
      type: pages
    values:
      menus:
        - "community"
  - scope:
      path: 'releasenotes'
      type: pages
    values:
      menus:
        - "releasenotes"
  - scope:
      path: 'apidocs'
      type: pages
    values:
      menus:
        - "apidocs"
  - scope:
      path: 'ATS'
      type: pages
    values:
      menus:
        - "ATS"
  - scope:
      path: 'APM'
      type: pages
    values:
      menus:
        - "APM"
  - scope:
      path: 'AQM'
      type: pages
    values:
      menus:
        #- "AQM"
  - scope:
      path: 'MXSDK'
      type: pages
    values:
      menus:
        - "MXSDK"
  - scope:
      path: 'howtogeneral'
      type: pages
    values:
      menus:
        - "howtogeneral"
  - scope:
      path: 'tips'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
  - scope:
      path: 'bestpractices'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "mendixcloud"
  - scope:
      path: 'mendixcloud'
      type: pages
    values:
      menus:
        - "howto6"
        - "tips"
        - "bestpractices"
        - "mendixcloud"

####################################

keep_files:
  - public
  - mappings
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.lock.osx
  - Gemfile.lock.win
  - _gulp
  - README.md
  - Rakefile
  - node_modules
  - Gulpfile.js
  - LICENSE
  - _assets
  - vendor
  - package.json
  - mappings.json
  - test.txt
  - run.bat
  - manifest_prod.yml
  - manifest_accp.yml
  - community/documentation/the-how-to-template.md
  - community/documentation/the-reference-guide-page-template.md
  - _data/assetsjs.json
  - _data/assetscss.json
  - CONTRIBUTING.md

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  syntax_highlighter: rouge
